CREATE TABLE recipe (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  url VARCHAR(500) NOT NULL,
  description TEXT NOT NULL,
  recipe TEXT NOT NULL,
  createdate TIMESTAMP,
  active BOOLEAN DEFAULT false,
  cook_time INT NOT NULL
);
